"""adds comments to all items classes

Revision ID: 088f22c811cc
Revises: 3b8bedc278b6
Create Date: 2022-06-30 22:10:13.720023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088f22c811cc'
down_revision = '3b8bedc278b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_hardware_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('hardware_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['hardware_item_id'], ['ci_hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_sla_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('sla_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['sla_item_id'], ['ci_sla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_software_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('software_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['software_item_id'], ['ci_software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_software_item')
    op.drop_table('comment_sla_item')
    op.drop_table('comment_hardware_item')
    # ### end Alembic commands ###
