"""adds item_type directly to ConfigurationItem instead of version 

Revision ID: 08f15edbcdb6
Revises: e6c8d877aa14
Create Date: 2022-06-18 10:08:06.450280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f15edbcdb6'
down_revision = 'e6c8d877aa14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ci_hardware', sa.Column('item_type', sa.String(length=20), nullable=False))
    op.add_column('ci_sla', sa.Column('item_type', sa.String(length=20), nullable=False))
    op.add_column('ci_software', sa.Column('item_type', sa.String(length=20), nullable=False))
    op.add_column('ci_hardware', sa.Column('last_version', sa.SmallInteger(), nullable=False))
    op.add_column('ci_sla', sa.Column('last_version', sa.SmallInteger(), nullable=False))
    op.add_column('ci_software', sa.Column('last_version', sa.SmallInteger(), nullable=False))
    op.drop_column('item_hardware_version', 'item_class')
    op.drop_column('item_sla_version', 'item_class')
    op.drop_column('item_software_version', 'item_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_software_version', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('item_sla_version', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('item_hardware_version', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('ci_software', 'item_type')
    op.drop_column('ci_sla', 'item_type')
    op.drop_column('ci_hardware', 'item_type')
    op.drop_column('ci_software', 'last_version')
    op.drop_column('ci_sla', 'last_version')
    op.drop_column('ci_hardware', 'last_version')
    # ### end Alembic commands ###
