"""add commentChange, commentProblem and commentIncident

Revision ID: 300a89e44846
Revises: c63103106c73
Create Date: 2022-06-12 17:09:02.621335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300a89e44846'
down_revision = 'c63103106c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_incident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_problem')
    op.drop_table('comment_incident')
    op.drop_table('comment_change')
    # ### end Alembic commands ###
