""" adds column is_blocked to Problem
Revision ID: 48e56a0884b8
Revises: c791a4798ab4
Create Date: 2022-06-02 20:18:30.511634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e56a0884b8'
down_revision = 'c791a4798ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'is_blocked')
    # ### end Alembic commands ###
