""" adds Hardware, SLA and Software Configuration Items to the database

Revision ID: 515f8e5273ed
Revises: a5b0b05d8578
Create Date: 2022-05-11 00:52:19.101956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515f8e5273ed'
down_revision = 'a5b0b05d8578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_hardware',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('item_family_id', sa.Integer(), nullable=True),
    sa.Column('item_class', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ci_sla',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('item_family_id', sa.Integer(), nullable=True),
    sa.Column('item_class', sa.String(length=20), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_manager', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=200), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('ending_date', sa.DateTime(), nullable=False),
    sa.Column('measurement_unit', sa.String(length=100), nullable=False),
    sa.Column('measurement_value', sa.Integer(), nullable=False),
    sa.Column('is_crucial', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ci_software',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('item_family_id', sa.Integer(), nullable=True),
    sa.Column('item_class', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('software_version', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ci_software')
    op.drop_table('ci_sla')
    op.drop_table('ci_hardware')
    # ### end Alembic commands ###
