"""adds restore_version logic to item versions

Revision ID: 681ad0738ddc
Revises: 7311e03fd2aa
Create Date: 2022-06-28 13:18:16.197372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681ad0738ddc'
down_revision = '7311e03fd2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_hardware_version', sa.Column('is_restoring_draft', sa.Boolean(), nullable=True))
    op.add_column('item_sla_version', sa.Column('is_restoring_draft', sa.Boolean(), nullable=True))
    op.add_column('item_software_version', sa.Column('is_restoring_draft', sa.Boolean(), nullable=True))
    op.add_column('item_hardware_version', sa.Column('restore_version_id', sa.Integer(), nullable=True))
    op.add_column('item_sla_version', sa.Column('restore_version_id', sa.Integer(), nullable=True))
    op.add_column('item_software_version', sa.Column('restore_version_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_software_version', 'is_restoring_draft')
    op.drop_column('item_sla_version', 'is_restoring_draft')
    op.drop_column('item_hardware_version', 'is_restoring_draft')
    op.drop_column('item_software_version', 'restore_version_id')
    op.drop_column('item_sla_version', 'restore_version_id')
    op.drop_column('item_hardware_version', 'restore_version_id')
    # ### end Alembic commands ###
