""" adds possible link to comments

Revision ID: 6f37119f55d3
Revises: 088f22c811cc
Create Date: 2022-07-02 11:45:41.219344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f37119f55d3'
down_revision = '088f22c811cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment_change', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_change', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_change', sa.Column('link_text', sa.String(length=500), nullable=True))
    op.add_column('comment_hardware_item', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_hardware_item', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_hardware_item', sa.Column('link_text', sa.String(length=500), nullable=True))
    op.add_column('comment_incident', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_incident', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_incident', sa.Column('link_text', sa.String(length=500), nullable=True))
    op.add_column('comment_problem', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_problem', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_problem', sa.Column('link_text', sa.String(length=500), nullable=True))
    op.add_column('comment_sla_item', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_sla_item', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_sla_item', sa.Column('link_text', sa.String(length=500), nullable=True))
    op.add_column('comment_software_item', sa.Column('has_link', sa.Boolean(), nullable=True))
    op.add_column('comment_software_item', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('comment_software_item', sa.Column('link_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment_software_item', 'link_text')
    op.drop_column('comment_software_item', 'link_url')
    op.drop_column('comment_software_item', 'has_link')
    op.drop_column('comment_sla_item', 'link_text')
    op.drop_column('comment_sla_item', 'link_url')
    op.drop_column('comment_sla_item', 'has_link')
    op.drop_column('comment_problem', 'link_text')
    op.drop_column('comment_problem', 'link_url')
    op.drop_column('comment_problem', 'has_link')
    op.drop_column('comment_incident', 'link_text')
    op.drop_column('comment_incident', 'link_url')
    op.drop_column('comment_incident', 'has_link')
    op.drop_column('comment_hardware_item', 'link_text')
    op.drop_column('comment_hardware_item', 'link_url')
    op.drop_column('comment_hardware_item', 'has_link')
    op.drop_column('comment_change', 'link_text')
    op.drop_column('comment_change', 'link_url')
    op.drop_column('comment_change', 'has_link')
    # ### end Alembic commands ###
