""" adds IncidentComment, ProblemComment, ChangeComment to the database

Revision ID: 7ef856a3b9b4
Revises: 7a431981826e
Create Date: 2022-06-10 19:26:34.956627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef856a3b9b4'
down_revision = '7a431981826e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_incident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_problem')
    op.drop_table('comment_incident')
    op.drop_table('comment_change')
    # ### end Alembic commands ###
