""" refactors User, removing innecessary fields and adding unique constraint on email

Revision ID: a5b0b05d8578
Revises: 73b3c4e6c288
Create Date: 2022-05-04 23:31:28.407921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5b0b05d8578'
down_revision = '73b3c4e6c288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'registered_on')
    op.drop_column('user', 'last_activity_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###
