""" adds Association tables between Configuration Items and Incidents

Revision ID: a7911f952b52
Revises: 08f15edbcdb6
Create Date: 2022-06-18 20:07:42.187735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7911f952b52'
down_revision = '6d1ea3d02057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_ci_item_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['hardware_ci_item_id'], ['ci_hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_ci_item_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sla_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['sla_ci_item_id'], ['ci_sla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_ci_item_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change.id'], ),
    sa.ForeignKeyConstraint(['software_ci_item_id'], ['ci_software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_ci_item_change')
    op.drop_table('sla_ci_item_change')
    op.drop_table('hardware_ci_item_change')
    # ### end Alembic commands ###
