""" adds column is_current_version to items

Revision ID: a8ada0e2f194
Revises: 48e56a0884b8
Create Date: 2022-06-04 21:54:46.916554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ada0e2f194'
down_revision = '48e56a0884b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ci_hardware', sa.Column('is_current_version', sa.Boolean()))
    op.add_column('ci_sla', sa.Column('is_current_version', sa.Boolean()))
    op.add_column('ci_software', sa.Column('is_current_version', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ci_software', 'is_current_version')
    op.drop_column('ci_sla', 'is_current_version')
    op.drop_column('ci_hardware', 'is_current_version')
    # ### end Alembic commands ###
