"""added change table

Revision ID: adef00e99cb4
Revises: a8ada0e2f194
Create Date: 2022-06-07 16:30:22.432096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adef00e99cb4'
down_revision = 'a8ada0e2f194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=75), nullable=True),
    sa.Column('taken_by', sa.String(length=75), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['taken_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change')
    # ### end Alembic commands ###
