""" creates Problem table

Revision ID: c791a4798ab4
Revises: c9c3c79ecb09
Create Date: 2022-05-31 11:11:48.136553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c791a4798ab4'
down_revision = 'c9c3c79ecb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('taken_by', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('impact', sa.String(length=20), nullable=True),
    sa.Column('cause', sa.String(length=1000), nullable=True),
    sa.Column('solution', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.username'], ),
    sa.ForeignKeyConstraint(['taken_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ci_hardware', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('ci_hardware', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ci_sla', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ci_software', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('incident', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'is_blocked')
    op.alter_column('ci_software', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ci_sla', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ci_hardware', 'item_class',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ci_hardware', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('incident_problem')
    op.drop_table('problem')
    # ### end Alembic commands ###
