""" adds intermediate tables for many-to-many relationship between incident and conf_item

Revision ID: c9c3c79ecb09
Revises: 515f8e5273ed
Create Date: 2022-05-11 01:23:44.694359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c3c79ecb09'
down_revision = '515f8e5273ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_ci_item_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_ci_item_id'], ['ci_hardware.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_ci_item_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sla_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['sla_ci_item_id'], ['ci_sla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_ci_item_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_ci_item_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['software_ci_item_id'], ['ci_software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_ci_item_incident')
    op.drop_table('sla_ci_item_incident')
    op.drop_table('hardware_ci_item_incident')
    # ### end Alembic commands ###
