""" adds solving date to solvables

Revision ID: d03f3b6ddae2
Revises: 9b2f4c32757e
Create Date: 2022-06-26 20:22:49.484043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03f3b6ddae2'
down_revision = '9b2f4c32757e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change', sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incident', sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('problem', sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'solved_at')
    op.drop_column('incident', 'solved_at')
    op.drop_column('change', 'solved_at')
    # ### end Alembic commands ###
