""" update known error version table

Revision ID: d50e91125419
Revises: a7911f952b52
Create Date: 2022-06-19 17:27:07.951137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50e91125419'
down_revision = 'a7911f952b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_error_version', sa.Column('created_by', sa.String(length=30), nullable=True))
    op.create_foreign_key("error_user_username", 'known_error_version', 'user', ['created_by'], ['username'])
    op.drop_column('known_error_version', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_error_version', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint("error_user_username", 'known_error_version', type_='foreignkey')
    op.drop_column('known_error_version', 'created_by')
    # ### end Alembic commands ###
