""" adds versions and modifies items tables to include these versions

Revision ID: e6c8d877aa14
Revises: e876ef6f8287
Create Date: 2022-06-18 00:44:00.028178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6c8d877aa14'
down_revision = 'e876ef6f8287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_hardware_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version_number', sa.SmallInteger(), nullable=False),
    sa.Column('item_class', sa.String(length=20), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['ci_hardware.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_sla_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version_number', sa.SmallInteger(), nullable=False),
    sa.Column('item_class', sa.String(length=20), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('service_manager', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=200), nullable=False),
    sa.Column('starting_date', sa.DateTime(), nullable=False),
    sa.Column('ending_date', sa.DateTime(), nullable=False),
    sa.Column('measurement_unit', sa.String(length=100), nullable=False),
    sa.Column('measurement_value', sa.Integer(), nullable=False),
    sa.Column('is_crucial', sa.Boolean(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['ci_sla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_software_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version_number', sa.SmallInteger(), nullable=False),
    sa.Column('item_class', sa.String(length=20), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('software_version', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['ci_software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ci_hardware', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.add_column('ci_hardware', sa.Column('draft_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ci_hardware_current_version_fk', 'ci_hardware', 'item_hardware_version', ['current_version_id'], ['id'])
    op.create_foreign_key('ci_hardware_draft_fk', 'ci_hardware', 'item_hardware_version', ['draft_id'], ['id'])
    op.drop_column('ci_hardware', 'item_family_id')
    op.drop_column('ci_hardware', 'is_current_version')
    op.drop_column('ci_hardware', 'version')
    op.drop_column('ci_hardware', 'serial_number')
    op.drop_column('ci_hardware', 'description')
    op.drop_column('ci_hardware', 'price')
    op.drop_column('ci_hardware', 'item_class')
    op.drop_column('ci_hardware', 'type')
    op.drop_column('ci_hardware', 'manufacturer')
    op.drop_column('ci_hardware', 'name')
    op.drop_column('ci_hardware', 'purchase_date')
    op.add_column('ci_sla', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.add_column('ci_sla', sa.Column('draft_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ci_sla_current_version_fk', 'ci_sla', 'item_sla_version', ['current_version_id'], ['id'])
    op.create_foreign_key('ci_sla_draft_fk', 'ci_sla', 'item_sla_version', ['draft_id'], ['id'])
    op.drop_column('ci_sla', 'item_family_id')
    op.drop_column('ci_sla', 'version')
    op.drop_column('ci_sla', 'is_current_version')
    op.drop_column('ci_sla', 'measurement_unit')
    op.drop_column('ci_sla', 'is_crucial')
    op.drop_column('ci_sla', 'description')
    op.drop_column('ci_sla', 'service_manager')
    op.drop_column('ci_sla', 'item_class')
    op.drop_column('ci_sla', 'service_type')
    op.drop_column('ci_sla', 'measurement_value')
    op.drop_column('ci_sla', 'name')
    op.drop_column('ci_sla', 'client')
    op.drop_column('ci_sla', 'starting_date')
    op.drop_column('ci_sla', 'ending_date')
    op.add_column('ci_software', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.add_column('ci_software', sa.Column('draft_id', sa.Integer(), nullable=True))
    op.create_foreign_key('ci_software_current_version_fk', 'ci_software', 'item_software_version', ['current_version_id'], ['id'])
    op.create_foreign_key('ci_software_draft_fk', 'ci_software', 'item_software_version', ['draft_id'], ['id'])
    op.drop_column('ci_software', 'item_family_id')
    op.drop_column('ci_software', 'software_version')
    op.drop_column('ci_software', 'is_current_version')
    op.drop_column('ci_software', 'version')
    op.drop_column('ci_software', 'description')
    op.drop_column('ci_software', 'item_class')
    op.drop_column('ci_software', 'type')
    op.drop_column('ci_software', 'provider')
    op.drop_column('ci_software', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ci_software', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('provider', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('is_current_version', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('software_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_software', sa.Column('item_family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('ci_software_current_version_fk', 'ci_software', type_='foreignkey')
    op.drop_constraint('ci_software_draft_fk', 'ci_software', type_='foreignkey')
    op.drop_column('ci_software', 'draft_id')
    op.drop_column('ci_software', 'current_version_id')
    op.add_column('ci_sla', sa.Column('ending_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('starting_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('client', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('measurement_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('service_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('service_manager', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('is_crucial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('measurement_unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('is_current_version', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('ci_sla', sa.Column('item_family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('ci_sla_current_version_fk', 'ci_sla', type_='foreignkey')
    op.drop_constraint('ci_sla_draft_fk', 'ci_sla', type_='foreignkey')
    op.drop_column('ci_sla', 'draft_id')
    op.drop_column('ci_sla', 'current_version_id')
    op.add_column('ci_hardware', sa.Column('purchase_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('item_class', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('serial_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('version', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('is_current_version', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ci_hardware', sa.Column('item_family_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('ci_hardware_current_version_fk', 'ci_hardware', type_='foreignkey')
    op.drop_constraint('ci_hardware_draft_fk', 'ci_hardware', type_='foreignkey')
    op.drop_column('ci_hardware', 'draft_id')
    op.drop_column('ci_hardware', 'current_version_id')
    op.drop_table('item_software_version')
    op.drop_table('item_sla_version')
    op.drop_table('item_hardware_version')
    # ### end Alembic commands ###
