""" Added missing solution field to Known Error Table

Revision ID: e876ef6f8287
Revises: 300a89e44846
Create Date: 2022-06-12 20:45:44.499250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e876ef6f8287'
down_revision = '300a89e44846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_error', sa.Column('solution', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('known_error', 'solution')
    # ### end Alembic commands ###
