"""adds version used column to 

Revision ID: f47ad609ddec
Revises: 6f37119f55d3
Create Date: 2022-07-07 02:25:39.663483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47ad609ddec'
down_revision = '6f37119f55d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_known_error', sa.Column('version_used', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident_known_error', 'version_used')
    # ### end Alembic commands ###
